### ISSUE TITLE
shark: '_' is not a valid option

### ISSUE THREAD

**Issue by anka-213** [fisherman/shark#11]
When you call shark without any arguments, you get the error `shark: '_' is not a valid option`.
This seems to be because getopts prints '_' if there are no arguments.

**Comment by bucaran** [comment]
Ah, yes, this must be a bug I introduced lately when fixing a problem with `getopts` removing duplicate arguments, which is a good thing, because there is nothing wrong with dupe arguments and that's up to the client to handle. 

I'll try to fix this right away, unless you want to take stab at it.

**Comment by anka-213** [comment]
Thanks. Please do so. My initial attempt at a fix failed.

(But I found a workaround of providing the argument '--')

**Comment by bucaran** [comment]
Fixed problem directly in `getopts`. Please update ```fisher update getopts``` and you try agian.
