### ISSUE TITLE
Font name

### ISSUE THREAD

**Issue by psmolak** [fisherman/shark#12]
Hi!

Would you mind sharing font name from gif below?

[https://cloud.githubusercontent.com/assets/8317250/12835057/122909f4-cbf0-11e5-86b3-9fd9956ebbb2.gif](https://cloud.githubusercontent.com/assets/8317250/12835057/122909f4-cbf0-11e5-86b3-9fd9956ebbb2.gif)

Thanks!

**Comment by bucaran** [comment]
Hi. I'm not 100% sure, but IIRC that one is Anonymous Pro.

* https://github.com/powerline/fonts/tree/master/AnonymousPro
